---
- name: Install fail2ban
  package:
    name: fail2ban
    state: present
  tags:
    - security
    - fail2ban

- name: Configure fail2ban
  template:
    src: fail2ban_jail.conf.j2
    dest: /etc/fail2ban/jail.conf
    mode: 0644
    owner: root
    group: root
    backup: yes
  notify:
    - restart fail2ban
    - persist iptables rules
  tags:
    - security
    - fail2ban
